apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-frontend
  name: udagram-frontend
spec:
  selector:
    matchLabels:
      run: udagram-frontend
  replicas: 1
  template:
    metadata:
      labels:
        run: udagram-frontend
        api: external
    spec:
      containers:
      - image: yahyabadawy/udagram-frontend:v3
        name: udagram-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
      restartPolicy: Always            